# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/mateo/OneDrive - ozixe/Bureau/Cours/projet_rubik/Zybo-Master.xdc

# Block Designs: bd/design1/design1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1 || ORIG_REF_NAME==design1} -quiet] -quiet

# IP: bd/design1/ip/design1_processing_system7_0_0/design1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_processing_system7_0_0 || ORIG_REF_NAME==design1_processing_system7_0_0} -quiet] -quiet

# IP: bd/design1/ip/design1_axi_bram_ctrl_0_0/design1_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_axi_bram_ctrl_0_0 || ORIG_REF_NAME==design1_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/design1/ip/design1_blk_mem_gen_0_0/design1_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_blk_mem_gen_0_0 || ORIG_REF_NAME==design1_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/design1/ip/design1_axi_smc_0/design1_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_axi_smc_0 || ORIG_REF_NAME==design1_axi_smc_0} -quiet] -quiet

# IP: bd/design1/ip/design1_rst_ps7_0_50M_0/design1_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_rst_ps7_0_50M_0 || ORIG_REF_NAME==design1_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/design1/ip/design1_memory_reader_IP_0_1/design1_memory_reader_IP_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_memory_reader_IP_0_1 || ORIG_REF_NAME==design1_memory_reader_IP_0_1} -quiet] -quiet

# IP: bd/design1/ip/design1_no_rebound_0_0/design1_no_rebound_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_no_rebound_0_0 || ORIG_REF_NAME==design1_no_rebound_0_0} -quiet] -quiet

# IP: bd/design1/ip/design1_rubik_resolver_0_0/design1_rubik_resolver_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_rubik_resolver_0_0 || ORIG_REF_NAME==design1_rubik_resolver_0_0} -quiet] -quiet

# XDC: bd/design1/design1_ooc.xdc
